version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - dependencies/dependabot
      - dependencies/go-modules
