## Ref: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configuration

changelog:
  exclude:
    labels:
      - ignore-for-release-notes
    authors:
      - dependabot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - release/major
        - breaking-change
    - title: New Features 🎉
      labels:
        - release/minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"
