---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spanner-autoscaller-secret-reader
  namespace: test
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames: ["gcp-sa-myproject-myspanner"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spanner-autoscaller-secret-reader
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spanner-autoscaller-secret-reader
subjects:
  - kind: ServiceAccount
    name: spanner-autoscaler-controller-manager
    namespace: spanner-autoscaler
