apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: spanner-autoscaler
  name: spanner-autoscaler-controller-manager
  namespace: spanner-autoscaler # kpt-set: ${namespace}
spec:
  replicas: 1 # kpt-set: ${replicas}
  selector:
    matchLabels:
      control-plane: spanner-autoscaler
  template:
    metadata:
      labels:
        control-plane: spanner-autoscaler
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        image: mercari/spanner-autoscaler:v0.1.5 # kpt-set: mercari/spanner-autoscaler:${version}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: spanner-autoscaler-controller-manager
      terminationGracePeriodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    control-plane: spanner-autoscaler
  name: spanner-autoscaler-controller-manager-metrics-service
  namespace: spanner-autoscaler # kpt-set: ${namespace}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: spanner-autoscaler
