apiVersion: apps/v1
kind: Deployment
metadata:
  name: spanner-autoscaler-controller-manager
  namespace: spanner-autoscaler # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
  labels:
    control-plane: spanner-autoscaler
spec:
  replicas: 2 # {"$ref":"#/definitions/io.k8s.cli.setters.replicas"}
  selector:
    matchLabels:
      control-plane: spanner-autoscaler
  template:
    metadata:
      labels:
        control-plane: spanner-autoscaler
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        command:
        - /manager
        image: mercari/spanner-autoscaler:v0.0.1 # {"$ref":"#/definitions/io.k8s.cli.substitutions.image"}
        name: manager
        resources:
          limits:
            cpu: 1
            memory: 200Mi
          requests:
            cpu: 500m
            memory: 100Mi
      terminationGracePeriodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    control-plane: spanner-autoscaler
  name: spanner-autoscaler-metrics-service
  namespace: spanner-autoscaler # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: spanner-autoscaler
