---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscalers
  - spannerautoscaleschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscalers/finalizers
  - spannerautoscaleschedules/finalizers
  verbs:
  - update
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscalers/status
  - spannerautoscaleschedules/status
  verbs:
  - get
  - patch
  - update
