
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resourceNames:
  - spanner-autoscaler-gcp-sa
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscaler/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscaleschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscaleschedules/finalizers
  verbs:
  - update
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscaleschedules/status
  verbs:
  - get
  - patch
  - update
