# permissions for end users to view spannerautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: spannerautoscaler-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spanner-autoscaler
    app.kubernetes.io/part-of: spanner-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: spannerautoscaler-viewer-role
rules:
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscalers/status
  verbs:
  - get
