# permissions for end users to view spannerautoscaleschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: spannerautoscaleschedule-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spanner-autoscaler
    app.kubernetes.io/part-of: spanner-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: spannerautoscaleschedule-viewer-role
rules:
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscaleschedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscaleschedules/status
  verbs:
  - get
