apiVersion: spanner.mercari.com/v1beta1
kind: SpannerAutoscaler
metadata:
  name: spannerautoscaler-sample-beta
spec:
  targetInstance:
    projectId: beta-project
    instanceId: beta-instance
  authentication:
    impersonateConfig:
      targetServiceAccount: dummy@example.iam.gserviceaccount.com
  scaleConfig:
    processingUnits:
      min: 100
      max: 500
    targetCPUUtilization:
      highPriority: 50
