apiVersion: spanner.mercari.com/v1alpha1
kind: SpannerAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: spannerautoscaler
    app.kubernetes.io/instance: spannerautoscaler-sample
    app.kubernetes.io/part-of: spanner-autoscaler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spanner-autoscaler
  name: spannerautoscaler-sample-alpha
  namespace: test
spec:
  scaleTargetRef:
    projectId: test-project
    instanceId: test-instance
  serviceAccountSecretRef:
    name: spanner-autoscaler-gcp-sa
    key: service-account
  minNodes: 1
  maxNodes: 4
  maxScaleDownNodes: 2
  targetCPUUtilization:
    highPriority: 80
