apiVersion: spanner.mercari.com/v1beta1
kind: SpannerAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: spannerautoscaler
    app.kubernetes.io/instance: spannerautoscaler-sample
    app.kubernetes.io/part-of: spanner-autoscaler
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spanner-autoscaler
  name: spannerautoscaler-sample-beta
  namespace: test
spec:
  targetInstance:
    projectId: beta-project
    instanceId: beta-instance
  authentication:
    impersonateConfig:
      targetServiceAccount: dummy@example.iam.gserviceaccount.com
  scaleConfig:
    processingUnits:
      min: 100
      max: 500
    targetCPUUtilization:
      highPriority: 50
