---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test
  name: spanner-autoscaller-service-account-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames: ["spanner-autoscaler-service-account"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: test
  name: spanner-autoscaller-service-account-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spanner-autoscaller-service-account-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: spanner-autoscaler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test
  name: spanner-autoscaller-event-publisher
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: test
  name: spanner-autoscaller-event-publisher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spanner-autoscaller-event-publisher
subjects:
  - kind: ServiceAccount
    name: default
    namespace: spanner-autoscaler
