apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spanner-autoscaler-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spanner-autoscaler-manager-role
subjects:
- kind: ServiceAccount
  name: spanner-autoscaler-controller-manager
  namespace: spanner-autoscaler # kpt-set: ${namespace}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spanner-autoscaler-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spanner-autoscaler-proxy-role
subjects:
- kind: ServiceAccount
  name: spanner-autoscaler-controller-manager
  namespace: spanner-autoscaler
