---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: spanner-autoscaler-manager-role
rules:
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spanner.mercari.com
  resources:
  - spannerautoscalers/status
  verbs:
  - get
  - patch
  - update
