apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spanner-autoscaler-leader-election-role-binding
  namespace: spanner-autoscaler # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spanner-autoscaler-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: spanner-autoscaler # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
