apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spanner-autoscaler-leader-election-rolebinding
  namespace: spanner-autoscaler # kpt-set: ${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spanner-autoscaler-leader-election-role
subjects:
- kind: ServiceAccount
  name: spanner-autoscaler-controller-manager
  namespace: spanner-autoscaler # kpt-set: ${namespace}
