---
apiVersion: v1
kind: Pod
metadata:
  name: spanner-autoscaler
  namespace: spanner-autoscaler
  labels:
    app: spanner-autoscaler
spec:
  containers:
    - name: spanner-autoscaler
      image: spanner-autoscaler
